server:
  port: 3344

spring:
  application:
    name:  springcloud-config-center #注册进Eureka服务器的微服务名
  cloud:
    config:
      server:
        git:
          uri: https://github.com/hql0512/springcloud-config.git #GitHub上面的git仓库名字
          username: hql0512
          password: huoquanlong0512
        ####搜索目录
          search-paths:
            - springcloud-config
      ####读取分支
      label: master

#服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka